source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'ProjectMarvel' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectMarvel
  pod 'Kingfisher', '~> 5.0'

  target 'ProjectMarvelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjectMarvelUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end