source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'HelloWorld' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloWorld
  pod 'Kingfisher', '~> 5.0'

  target 'HelloWorldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HelloWorldUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
